---
- name: install apache
  hosts: webserver
  collections:
    - geerlingguy.php_roles
  roles:
    - php
    - role: php-versions
      vars:
        php_version: '7.3'

# install from ansible Galaxy
- name: install mysql
  hosts: database
  roles:
    - role: geerlingguy.mysql
      become: yes


      